version: "3.7"

services:
  cuzoo-frontend:
    image: cuzoo/frontend:latest
    container_name: cuzoo-frontend
    links:
      - cuzoo-backend
    ports:
      - "127.0.01:8082:80"

  cuzoo-backend:
    image: cuzoo/backend:latest
    container_name: cuzoo-backend
    depends_on:
      - "postgre-db"
    ports:
      - "127.0.0.1:8083:5000"
    command:
      ["java", "-jar", "/app/app.jar",
       "--spring.datasource.url=jdbc:postgresql://postgre-db:5432/postgre-db",
       "--spring.datasource.username=postgres",
       "--spring.datasource.password=secure",
       "--spring.datasource.driver-class-name=org.postgresql.Driver",
       "--spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect",
       "--spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true",
       "--server.port=5000"
      ]

  postgre-db:
    image: postgres:9.5
    container_name: postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure
      - POSTGRES_DB=postgre-db
