version: "3.7"

services:
  cuzoo-frontend:
    image: cuzoo/frontend:latest
    build: "frontend"
    container_name: cuzoo-frontend
    links:
      - cuzoo-backend
    ports:
      - "127.0.01:8084:80"

  cuzoo-backend:
    image: cuzoo/backend:latest
    build: "backend"
    container_name: cuzoo-backend
    ports:
      - "127.0.0.1:8085:5000"
    command:
      ["java", "-jar", "/app/app.jar",
       "--spring.datasource.url=jdbc:h2:mem:testdb",
       "--spring.datasource.username=sa",
       "--spring.datasource.password=password",
       "--spring.datasource.driver-class-name=org.h2.Driver",
       "--spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect",
       "--spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true",
       "--spring.jpa.hibernate.ddl-auto=create",
       "--spring.profiles.active=demo",
       "--server.port=5000"
      ]
