ALTER SEQUENCE attachment_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE company_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE contact_point_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE contact_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE label_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE opportunity_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE todo_seq RESTART WITH 1000 INCREMENT BY 1;
ALTER SEQUENCE user_seq RESTART WITH 1000 INCREMENT BY 1;